version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - cat test.js
      - node test.js
  post_build:
    commands:
      - cat test.js
      - pwd
      - node test.js

artifacts:
  discard-paths: yes
